---
title: "PostgreSQL/PostGIS without instllation"
author: "Shipeng Sun"
date: "2022-07-01"
slug: "postgresql-start-cmd"
categories: Database
tags:
- PostgreSQL
- PostGIS
- geospatial database
type: ''
subtitle: ''
image: ''
---

[Using EnterpriseDB installer to install PostgreSQL](https://www.postgresql.org/download/windows/) and [using Stackbuilder to install PostGIS](http://www.bostongis.com/PrinterFriendly.aspx?content_name=postgis_tut01) is very easy. However, running PostgreSQL/PostGIS as a service, which is the default result of such installations, has some overhead because it is running in the background no matter it is actually used or not. Note that PostgreSQL has a small footprint when in "idle". Nevertheless, it could be useful to run PostgreSQL/PostGIS as needed using binaries.

## Download PostgreSQL and PostGIS Binaries

PostgreSQL and PostGIS binaries are executable files and can run without installation. Here are a few good sources for information.

[Stack Overflow](https://stackoverflow.com/questions/26441873/starting-postgresql-and-pgadmin-in-windows-without-installation)

[Enterprise DB Binaries for PostgreSQL](https://www.enterprisedb.com/download-postgresql-binaries)

[PostGIS Zip Files](https://postgis.net/windows_downloads/)

[Command to start/stop PostgreSQL](https://www.postgresonline.com/journal/archives/172-Starting-PostgreSQL-in-windows-without-install.html)

The basic process is to unzip the PostgreSQL to a folder. Then unzip the PostGIS binary and overwrite those in PostgreSQL.

## Commands to manage PostgreSQL/PostGIS

```{bash postgresql-cmd,  eval=FALSE}

@ECHO Change to the bin folder of the downloaded/unzipped PostgreSQL Binaries
@ECHO Intialize a database cluster (data folder/directory) using initdb with -D

initdb -D c:\Users\Arthur\pgdata -U postgres -W -E UTF8 -A scram-sha-256


```

Then, create a batch file to start, stop PostgreSQL

```{bash startpostgres, eval = FALSE}

@ECHO OFF

REM Initialize the database cluster using a data folder
REM C:\PortableSoftware\pgsql\bin\initdb -D C:\PortableSoftware\pgsql\data

REM Start the service with a log file
C:\PortableSoftware\pgsql\bin\pg_ctl.exe -D C:\PortableSoftware\pgsql\data -l C:\PortableSoftware\pgsql\bin\pg.log start 

@ECHO Press any key three times to stop the service ... 
PAUSE
PAUSE
PAUSE

REM STOP the service
C:\PortableSoftware\pgsql\bin\pg_ctl.exe -D C:\PortableSoftware\pgsql\data stop


```

The above is to start PostgreSQL and below is to stop it.

```{bash stoppostgres, eval=FALSE}

@ECHO OFF

REM Initialize the database using a data folder
REM C:\PortableSoftware\pgsql\bin\initdb -D C:\PortableSoftware\pgsql\data

REM Start the service with a log file
REM C:\PortableSoftware\pgsql\bin\pg_ctl.exe -D C:\PortableSoftware\pgsql\data -l pg.log start

REM STOP the service
C:\PortableSoftware\pgsql\bin\pg_ctl.exe -D C:\PortableSoftware\pgsql\data stop


```
