---
title: "Read New on new Reader"
author: "Shipeng Sun"
date: "2022-07-17"
slug: Setting up new ebook reader
categories: Settings
tags:
- ereader
- fonts
- computer settings
- ebook
type: ''
subtitle: ''
image: ''
---

Acquired a new ebook reader Rakuten Kobo Elipsa. The device has a good size at 10 inch. It also supports Dropbox for loading books and OverDrive for borrowing from public libraries.  

A few useful settings:

- [DoubleCommander](https://github.com/doublecmd/): A open-source alternative to TotalCommander. A more powerful and more convenient file explorer.

- [Briss](http://briss.sourceforge.net/): A open source PDF cropper. It is running on Java. Windows removes Java by default, but many programs, like ArcGIS Pro, installed their own Java Running Environment (JRE). So, there is no need to install a new Java. Just use an existing one. 

```{bash briss-java, eval=FALSE}

# Either add Java to Path or use the full path of Java.exe to run briss

C:\Program Files\ArcGIS\Pro\java\runtime\jre\bin\java.exe -jar .\briss.jar

```

- Extra fonts: for CN fonts, the [WenKai](https://github.com/lxgw/LxgwWenKai/) font is very decent for ebook readers. For EN fonts, Google has a list of interesting fonts at fonts.google.com, although most devices also come with pretty good fonts. On Kobo Elipsa, these fonts can be directly copied to the fonts folder (subfolders also work).


