---
title: "Items in Action"
author: "Shipeng Sun"
date: "2022-11-29"
slug: []
categories: Efficiency Tool
tags: 
- web resources
- initiatives
- future directions
type: ''
subtitle: ''
image: ''
---

This is an ongoing list of items in actions, aka list of TODO items. So often, some good directions that deserve serious investigations and explorations have to be put off. This blog is trying to make a record of these resources.

## Open Geospatial Data

- [White House Transparency and Open Government](https://obamawhitehouse.archives.gov/the-press-office/transparency-and-open-government)
- [Open data: an international comparison of strategies](http://www.mediafutureweek.nl/wp-content/uploads/2011/06/Open-data_ePractice-Journal_final_30122010.pdf)

- [Harvard CGA China Data Links](http://gis2.harvard.edu/resources/data/china-gis-data)

- [USGS Data Quality Assurance Best Practice and Examples](https://www.usgs.gov/data-management/quality-assurance-plans-recommended-practices-and-examples?qt-science_support_page_related_con=0#qt-science_support_page_related_con)

- [NYC Open Data Dashboard](https://opendata.cityofnewyork.us/dashboard/)

## Web Scraping

- [Web scraping using rvest](https://www.scrapingbee.com/blog/web-scraping-r/#web-scraping-using-rvest)


## NYC GTFS

- [nyc subway real-time data](https://github.com/toddwschneider/nyc-subway-data)
- [Using Countdown Clock Data to Understand the New York City Subway](https://toddwschneider.com/posts/nyc-subway-data-analysis/)
- [New Yorker Subway Inequality](https://projects.newyorker.com/story/subway/)

## Deep Learning and AI

- [Deep learning with satellite & aerial imagery](https://github.com/robmarkcole/satellite-image-deep-learning)
- [satellite image training datasets with annotations for computer vision and deep learning](https://github.com/chrieke/awesome-satellite-imagery-datasets)
- [OpenMMLab Detection Toolbox and Benchmark](https://github.com/open-mmlab/mmdetection)
- [YOLOR - You Only Look Once Representation](https://viso.ai/deep-learning/yolor/)


## Redistricting and Gerrymandering

- [New York State Redistricting](https://www.nyirc.gov/plans)
- [New York State Official District Maps](https://latfor.state.ny.us/maps/)
- [Redistricting in every state](https://projects.fivethirtyeight.com/redistricting-2022-maps/georgia/)

## Shape Transformation

- [transformr: R package for animated shape transformation](https://github.com/thomasp85/transformr)

- [flubber: JavaScript library for shape transformation or interpolation](https://github.com/veltman/flubber)

- [Animated Cartograms](https://github.com/ESO-Rennes/Animated-Cartograms/blob/main/pulsations_final.Rmd)

## Flow Visualization

- [Large scale flow movement visualization](https://github.com/cambecc/earth)
- [Mapbox + WebGL](https://blog.mapbox.com/how-i-built-a-wind-map-with-webgl-b63022b5537f)

## ArcGIS Development

- [ArcGIS Pro SDK for Add-in Development](https://github.com/Esri/arcgis-pro-sdk)
- [.Net MAUI Multi-platform UI](https://learn.microsoft.com/en-us/training/modules/build-mobile-and-desktop-apps/1-introduction)
- [.NET MAUI Tutorial](https://dotnet.microsoft.com/en-us/learn/maui/first-app-tutorial/next)

## Temporal Modeling

- [Events Data](http://data.gdeltproject.org/events/index.html)

## Geography History

- [Yi-Fu Tuan, Lost in Place](https://www.chronicle.com/article/lost-in-place/)

<!---
## Personal Matters

- [Dr. Tatiana Sarkisian, DDS](https://www.zocdoc.com/dentist/tatiana-sarkisian-dds-19949?LocIdent=17877&reason_visit=12&insuranceCarrier=235&insurancePlan=1854&dr_specialty=98&isNewPatient=true)

- [Dr. Demetrios Mihalos, DDS](#)
- [Dr. Daniel Wank, DDS. Same location as Dr. Mihalos. Looks like the owner](#)

- [Dr. Snehasree Mohan, DMD](#)

--->